CREATE TABLE creditos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   credit_code UUID NOT NULL,
   credit_value DECIMAL NOT NULL,
   day_first_installment date NOT NULL,
   number_of_installment INT NOT NULL,
   status SMALLINT,
   customer_id BIGINT,
   CONSTRAINT pk_creditos PRIMARY KEY (id)
);

ALTER TABLE creditos ADD CONSTRAINT uc_creditos_credit_code UNIQUE (credit_code);

ALTER TABLE creditos ADD CONSTRAINT FK_CREDITOS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES cliente (id);