services:
  nlw-agents-pg:
    image: pgvector/pgvector:pg17 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nlw_agents
    ports:
      - "5432:5432" # redireciona a porta 5432 do container para a porta 5432 do host
    volumes: # This volume is used to persist the database data
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql # This file is executed when the container starts